# tcp-healthz GitLab CI config
before_script:
  - export VERSION=$(git describe --tags --always --dirty)
  - mkdir -p /go/src/github.com/apprenda/tcp-healthz
  - ln -s /builds/kismatic/tcp-healthz /go/src/github.com/apprenda/tcp-healthz
  - cd /go/src/github.com/apprenda/tcp-healthz

stages:
  - build
  - push

build:
  image: golang:1.8
  stage: build
  script:
    - make build
  artifacts:
    paths:
      - bin/

push:
  image: docker:dind
  stage: push
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD -e $DOCKER_EMAIL
    - make push
