kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: gluster-healthz
spec:
  template:
    metadata:
      labels:
        app: gluster-healthz
    spec:
      containers:
        - name: tcp-healthz
          image: apprenda/tcp-healthz-amd64:latest
          command: ["/exechealthz"]
          args:
            - -cmd=/tcp-healthz-amd64 --ports 111,2049,38465,38466,38467
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 2
      hostNetwork: true
      nodeSelector:
        gluster: "true"
