kind: Service
apiVersion: v1
metadata:
  name: gluster-healthz
spec:
  selector:
    app: gluster-healthz
  ports:
    - name: rpcbind
      port: 111
    - name: nfs
      port: 2049
    - name: gluster-nfs-38465
      port: 38465
    - name: gluster-nfs-38466
      port: 38466
    - name: gluster-nfs-38467
      port: 38467
